### PR TITLE
exploratory analysis for staggered grid implementation

### LINKED ISSUE #255: Staggered grids
Hi everyone,

I want to use staggered grids in this package, but this is yet to be a feature. I wanted to try to implement it, but I still need to get more familiar with the inner working of this package. Would anybody be able to give me any tips on where to start?

Cheers.

### PR DESCRIPTION
**Pull request by cmhyett**
working to fix #255

### CODE REVIEW

**Comment by cmhyett** [comment]
To add a bit more detail - my guiding example is the wave equation, following:
Staggered Time Integrators for Wave Equations Michelle Ghrist and Bengt Fornberg and Tobin A. Driscoll

Currently, one can implement the wave equation with periodic B.C.'s in MoL as:
```
using OrdinaryDiffEq, ModelingToolkit, MethodOfLines, DomainSets, Plots;

@parameters t x
@variables ρ(..) ϕ(..)
Dt = Differential(t);
Dx = Differential(x);

a = 0.1;
L = 10.0;

eq = [Dt(ρ(t,x)) + Dx(ϕ(t,x)) ~ 0,
      Dt(ϕ(t,x)) + a^2 * Dx(ρ(t,x)) ~ 0]
bcs = [ρ(0.0,x) ~ exp(-(x-L/2)^2),
       ϕ(0.0,x) ~ 0.0,
       ρ(t,0) ~ ρ(t,L),
       ϕ(t,0) ~ ϕ(t,L)];


domains = [t in Interval(0.0, 100.0),
           x in Interval(0.0, L)];

@named pdesys = PDESystem(eq, bcs, domains, [t,x], [ρ(t,x), ϕ(t,x)]);

dx = 0.1;
# must use WENO, otherwise upwind is default, biasing one direction
discretization = MOLFiniteDifference([x=>dx], t, advection_scheme=WENOScheme());

prob = discretize(pdesys, discretization);

sol = solve(prob, RK4(), saveat=10.0, dt=dx);
p = plot();
for i in 1:length(sol[t])
    plot!(p, sol[x], sol[ρ(t,x)][i,:], label="t = $(sol[t][i])")
end
display(p)
```
waveEq

**Comment by cmhyett** [comment]
The simplest PDE we can utilize staggered grids for is the 1D wave equation, with periodic boundary conditions as written in the code block above. If we discretize this  on staggered space and time, we obtain the update rules:
$$\rho_x^{t+1} = \rho_x^{t-1} - \left(\frac{\Delta t}{\Delta x}\right) \left( \phi_{x+1}^t - \phi_{x-1}^t \right) \ ; \qquad \phi_x^{t+1} = \phi_x^{t-1} - \left(a^2 \cdot \frac{\Delta t}{\Delta x}\right) \left( \rho_{x+1}^t - \rho_{x-1}^t \right)$$

Where the $x,t$'s in the $\rho$ update are distinct from the $x,t$'s in the $\phi$ update.

Next step is to write functionality to generate these grids...as mentioned in the above reference, time/space staggering may be independently desired, so I think it best that these are in fact distinct space grids (values in between solved grid points can simply be interpolated after the fact).

**Comment by cmhyett** [comment]
Just an update here - slow progress. 

Many responsibilities split between PDEBase and MethodOfLines. Ultimately, the functionality to do the differencing already exists - I'm simply trying to generate code to compute centered finite differences in two steps. The rigidity is coming from an interaction between the two packages, where MethodOfLines refuses to leave dangling variables (fair), and once passing a system of equations to PDEBase, it fully discretizes them into a single function (also fair).

I think the most logical entry point here is to overwrite the PDEBase orchestrating "discretize", but this has such nice generality I've hesitated thus far, looking for a downstream entry...

Additionally, MethodOfLines does a good job ensuring a 1-1 matching of equations and unknowns, splitting the functionality into two functions makes this more difficult...

One could do this all in one go, i.e. write a new set of rules to discretize the space differential to do the staggering, but this gives away a lot of flexibility, and I don't see it generalizing to other space/time/boundary staggering easily - meaning it really doesn't solve the fundamental issue.

One could overwrite the MoL pass, checking for staggering type, breaking the pdesystem into component equations (and BCs) to be solved on the whole and half steps, removing the looping over all dependent variables (only generate functions for the variable the equation is for...this is identified somewhere), and instead loop over all such sets of eq=>var pairs. Only after all the discretization has been done, and whole and half timestep functions generated will we do the basic checks. This is probably best path forward.

**Comment by xtalax** [comment]
Maybe this is a failure in segregation, the split between PDEBase and MOL is quite new and malleable, can you envisage a demarcation that would make this easier?

In any case, supporting all bcs in this scheme is hard. You are free to throw out the difficult to support the possible. Working out what the demarcation should be is the most difficult problem here. Do you have an intuition?

**Comment by xtalax** [comment]
For context, no other discretizer currently uses anything outside of the variable map,  and the tools in `symbolic_utils.jl`.
I want to understand whether `symbolic_discretize` is a general procedure or if it belongs in MOL and all discretizers implement this manually.

**Comment by cmhyett** [comment]
Yeah, I think you cut to the heart of the issue. I want to say you could do it without ownership of `symbolic_discretize` (it lowers developer overhead and the generality of the unified implementation is certainly compelling). 

Unfortunately, I think you might run into similar issues for other solution methods, for example operator splitting.
https://docs.sciml.ai/DiffEqDocs/latest/types/split_ode_types/

I'll first overwrite `symbolic_discretize` to get something working, and then perhaps it'll be easier to determine if the heavy hammer was necessary.

**Comment by cmhyett** [comment]
Even specializing `SciMLBase.discretize` isn't enough, as the engine of `structural_simplify` again forces closing the system of equations before generating a function (`ExtraVariablesSystemException`)

Much of this effort is to navigate around the constraint of closing equations at the individual function level - i.e. `f(u, p, t)` *must* update all components of `u` or we run into errors at essentially every step.

This doesn't seem like a fundamental limitation though - if one can generate from symbolics a function that updates all variables, one should also have the ability to generate a function that updates a subset...

I think next step is to diagram the flow and blocking functionality so we can discuss what to target with better visibility.

**Comment by xtalax** [comment]
Good point, this will probably need an update to MTK to fix

**Comment by cmhyett** [comment]
Incremental update, via suggestions from @xtalax @ChrisRackauckas, used "symbolic tracing" to translate the single generated update function into two updates (integer and half-step updates).

Currently _very_ hacky, but possible to see how this can be translated. Hurdles now are to

1. allow space staggering (this example is only time-staggered, not space). 
2. solve the PDE, create regression test.
3. agree where this step fits, implement mvp and ask for PR review
4. once interior can be time and/or space staggered using periodic BCs, we can begin handling more general conditions.

```
using OrdinaryDiffEq, ModelingToolkit, MethodOfLines, DomainSets, Plots;

@parameters t x
@variables ρ(..) ϕ(..)
Dt = Differential(t);
Dx = Differential(x);

a = 0.1;
L = 3.0;
dx = 1.0;

initialFunction(x) = relu(x-L/4) - 2*relu(x-(2*L/4)) + relu(x-(3*L/4))

eq = [Dt(ρ(t,x)) + Dx(ϕ(t,x)) ~ 0,
      Dt(ϕ(t,x)) + a^2 * Dx(ρ(t,x)) ~ 0]
bcs = [ρ(0.0,x) ~ exp(-(x-L/2)^2),
       ϕ(0.0,x) ~ 0.0,
       ρ(t,0) ~ ρ(t,L),
       ϕ(t,0) ~ ϕ(t,L)];


domains = [t in Interval(0.0, 10.0),
           x in Interval(0.0, L)];

@named pdesys = PDESystem(eq, bcs, domains, [t,x], [ρ(t,x), ϕ(t,x)]);

discretization = MOLFiniteDifference([x=>dx], t, grid_align=MethodOfLines.CenterAlignedGrid());
#discretization = MOLFiniteDifference([x=>dx], t, grid_align=MethodOfLines.StaggeredGrid());

prob = discretize(pdesys, discretization);

#prob.f now has the generated function, want to symbolic trace to get integer and half step
# iterations
@variables rho[1:3] phi[1:3]

# choose which outputs we want..
drho = (prob.f([collect(rho); collect(phi)], nothing, 0.0)[1:3]);
dphi = (prob.f([collect(rho); collect(phi)], nothing, 0.0)[4:6]);

gen_drho = eval(Symbolics.build_function(drho, collect(rho), collect(phi))[2]);
gen_dphi = eval(Symbolics.build_function(dphi, collect(rho), collect(phi))[2]);

dynamical_f1(drho,rho,phi,p,t) = gen_drho(drho, rho, phi);
dynamical_f2(dphi,rho,phi,p,t) = gen_dphi(dphi, rho, phi);
prob = DynamicalODEProblem(dynamical_f1, dynamical_f2, prob.u0[1:3], prob.u0[4:6], (0.0,1.0))
```

**Comment by xtalax** [comment]
Disgusting hack, bit of it works it isn't stupid!

**Comment by cmhyett** [comment]
Looking at commit history, I don't want to keep many of the hacks I put in place here - for ease of review I'll let that branch die and simply start fresh.

**Pull request closed without merging**
