### PR TITLE
Fix first tutorial

### PR DESCRIPTION
**Pull request by ArnoStrouwen**
First tutorial is broken in several places.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
I think @xtalax fixed some tutorials and added doctests in https://github.com/SciML/MethodOfLines.jl/pull/99 ? Everything should use doctests. Let's make sure these two PRs are aligned though.

**Comment by ArnoStrouwen** [comment]
Everything I change here is also addressed there.
If there is still more work to be done on that larger overhaul, it might be a good idea to merge this in so users don't get a bad first impression.

**Comment by ChrisRackauckas** [comment]
I'd hope that PR merges in like the next 2 days. I thought it was just caught up on some Bruss doctest segfault and would be ready to merge this morning.

**Comment by ChrisRackauckas** [comment]
What's left?

**Comment by ArnoStrouwen** [comment]
Nothing left, I think.

**Pull request closed without merging**
