### PR TITLE
Attempt to add API reference

### PR DESCRIPTION
**Pull request by MilkshakeForReal**

### CODE REVIEW

**Comment by MilkshakeForReal** [comment]
BTW, is `axies` a typo?

**Comment by ChrisRackauckas** [comment]
Looks like it. It's probably worth fixing. Though it would be good to choose a name that doesn't cause shadowing.

**Comment by MilkshakeForReal** [comment]
What drove me to write these docstrings was that I found it hard to understand the source code of MOL. With these at least I can understand the most part of http://methodoflines.sciml.ai/dev/devnotes/.

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by MilkshakeForReal** [comment]
There's a lot of naming worth fixing...

**Comment by ChrisRackauckas** [comment]
That's always easy to do right before dropping the next major (or here, v1.0), so I never tend to worry about it until there's a sense they will lock in. But if you wish to correct a few, please don't shy away.

**Comment by xtalax** [comment]
Axies was originally a typo, I decided to leave it to avoid shadowing but am open to other ideas. As for a lot of the shorter more euphemistic names like `s` `x\bar` `u\bar` and `x2i` having them longer really interferes with readability in a lot of the longer statements since they are used so frequently.

**Comment by xtalax** [comment]
Thank you for this!

**Comment by MilkshakeForReal** [comment]
We have talked about this. Annotating the type of `s` is a very good start. I'm not saying that variable names should simply be longer. But they should meet the standards of clean code. Like changing `params` to `spvars` or `get_spvars` would be much better. Also sometimes the discretization is very slow and there seems to be a lot of room for performance improvement

**Comment by ChrisRackauckas** [comment]
> Also sometimes the discretization is very slow and there seems to be a lot of room for performance improvement

Right now the code size is O(1/dx), i.e. if you have more discretization points then you have a larger code size. That is due to the scalarization in the IR. It needs to change to O(1) before we can call the library complete, and that's what the stencil forms and symbolic IR stuff is all about.

**Comment by xtalax** [comment]
I find `spvars` quite undescriptive, this is `params` to reference how they are generated i.e. with `@parameters`. I would support changing this to `get_params` however.

**Pull request merged**
