### PR TITLE
Integration over the whole domain

### LINKED ISSUE #94: Feature request: support for integral terms
Help! All the PDE models I'm interested in integrate over one of the dimensions, and `NeuralPDE.jl` is too slow for many of them. As MOL is the standard way to discretize these models in the literature, would it be possible to add in support for integrals?

### PR DESCRIPTION
**Pull request by xtalax**
Due to a limitation, the whole domain integral needs to have the same arguments as the integrand, but is constant in `x`. To use it in an equation one dimension lower, use a boundary value like `integral(t, 0.0)`
```
    # test integrals
    @parameters t, x
    @variables integrand(..) integral(..)
    Dt = Differential(t)
    Dx = Differential(x)
    xmin = 0.0
    xmax = 2.0 * pi

    Ix = Integral(x in DomainSets.ClosedInterval(xmin, xmax)) # integral over domain

    eqs = [integral(t, x) ~ Ix(integrand(t, x))
        integrand(t, x) ~ t * cos(x)]

    bcs = [intergral(0, x) ~ 0.0,
        integrand(0, x) ~ 0.0]

    domains = [t ∈ Interval(0.0, 1.0),
        x ∈ Interval(xmin, xmax)]

    @named pde_system = PDESystem(eqs, bcs, domains, [t, x], [integrand(t, x), integral(t, x)])

    asf(t) = 0.0

    disc = MOLFiniteDifference([x => 120], t)

    prob = discretize(pde_system, disc)

    sol = solve(prob, Tsit5())

    xdisc = sol[x]
    tdisc = sol[t]

    integralsol = sol[integral(t, x)]
    exact = [asf(t_) for t_ in tdisc, x_ in xdisc]
```

fixes #94

### CODE REVIEW

**Comment by sdwfrost** [comment]
Thanks! I tried this out on my two examples which are normally solved via MOL.

Example 1 discretizes, but fails at solve.

```julia
using ModelingToolkit
using MethodOfLines
using DomainSets
using OrdinaryDiffEq

@parameters t a
@variables S(..) I(..) R(..)
Dt = Differential(t)
Da = Differential(a)
Ia = Integral(a in DomainSets.ClosedInterval(0,52*75.0))

β = 0.0005
γ = 0.25

eqs = [Dt(S(a,t)) + Da(I(a,t)) ~ -β * S(a,t) * Ia(I(a,t)),
       Dt(I(a,t)) + Da(I(a,t)) ~ -γ*I(a,t),
       Dt(R(a,t)) + Da(R(a,t)) ~ γ*I(a,t)];

bcs = [
        S(a,0) ~ 990.0/(75*52),
        S(0,t) ~ 0.0,
        I(a,0) ~ 10.0/(75*52),
        I(0,t) ~ 0.0,
        R(a,0) ~ 0.0,
        R(0,t) ~ 0.0
        ]

domains = [t ∈ (0,40.0), a ∈ (0,75*52)]

@named pde_system = PDESystem(eqs, bcs, domains, [a, t], [S(a, t), I(a, t), R(a, t)])
da = 52
discretization = MOLFiniteDifference([a=>da],t)

prob = MethodOfLines.discretize(pde_system, discretization)
sol = solve(prob, Tsit5())
```

Output:

```julia
julia> sol = solve(prob, Tsit5())
ERROR: MethodError: Cannot `convert` an object of type SymbolicUtils.Add{Float64, Float64, Dict{Any, Number}, Nothing} to an object of type Float64
Closest candidates are:
  convert(::Type{T}, ::Unitful.Gain) where T<:Real at ~/.julia/packages/Unitful/fbiNW/src/logarithm.jl:62
  convert(::Type{T}, ::Unitful.Level) where T<:Real at ~/.julia/packages/Unitful/fbiNW/src/logarithm.jl:22
  convert(::Type{T}, ::Unitful.Quantity) where T<:Real at ~/.julia/packages/Unitful/fbiNW/src/conversion.jl:145
  ...
Stacktrace:
  [1] setindex!(A::Vector{Float64}, x::SymbolicUtils.Add{Float64, Float64, Dict{Any, Number}, Nothing}, i1::Int64)
    @ Base ./array.jl:903
  [2] macro expansion
    @ ~/.julia/packages/SymbolicUtils/qulQp/src/code.jl:394 [inlined]
  [3] macro expansion
    @ ~/.julia/packages/Symbolics/FGTCH/src/build_function.jl:519 [inlined]
  [4] macro expansion
    @ ~/.julia/packages/SymbolicUtils/qulQp/src/code.jl:351 [inlined]
  [5] macro expansion
    @ ~/.julia/packages/RuntimeGeneratedFunctions/6v5Gn/src/RuntimeGeneratedFunctions.jl:137 [inlined]
  [6] macro expansion
    @ ./none:0 [inlined]
  [7] generated_callfunc
    @ ./none:0 [inlined]
  [8] (::RuntimeGeneratedFunctions.RuntimeGeneratedFunction{(:ˍ₋out, :ˍ₋arg1, :ˍ₋arg2, :t), ModelingToolkit.var"#_RGF_ModTag", ModelingToolkit.var"#_RGF_ModTag", (0xcb0eae81, 0xc1f457d0, 0x4567074d, 0xab381c5c, 0x7871df2a)})(::Vector{Float64}, ::Vector{Float64}, ::SciMLBase.NullParameters, ::Float64)
    @ RuntimeGeneratedFunctions ~/.julia/packages/RuntimeGeneratedFunctions/6v5Gn/src/RuntimeGeneratedFunctions.jl:124
  [9] f
    @ ~/.julia/packages/ModelingToolkit/gZ57L/src/systems/diffeqs/abstractodesystem.jl:285 [inlined]
 [10] ODEFunction
    @ ~/.julia/packages/SciMLBase/VKnrY/src/scimlfunctions.jl:2096 [inlined]
 [11] initialize!(integrator::OrdinaryDiffEq.ODEIntegrator{Tsit5{typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.trivial_limiter!), Static.False}, true, Vector{Float64}, Nothing, Float64, SciMLBase.NullParameters, Float64, Float64, Float64, Float64, Vector{Vector{Float64}}, ODESolution{Float64, 2, Vector{Vector{Float64}}, Nothing, Nothing, Vector{Float64}, Vector{Vector{Vector{Float64}}}, ODEProblem{Vector{Float64}, Tuple{Float64, Float64}, true, SciMLBase.NullParameters, ODEFunction{true, SciMLBase.AutoSpecialize, ModelingToolkit.var"#f#486"{RuntimeGeneratedFunctions.RuntimeGeneratedFunction{(:ˍ₋arg1, :ˍ₋arg2, :t), ModelingToolkit.var"#_RGF_ModTag", ModelingToolkit.var"#_RGF_ModTag", (0xeacbf879, 0x8cf5ba36, 0xa4c23b0f, 0x3fc01e9a, 0x21768875)}, RuntimeGeneratedFunctions.RuntimeGeneratedFunction{(:ˍ₋out, :ˍ₋arg1, :ˍ₋arg2, :t), ModelingToolkit.var"#_RGF_ModTag", ModelingToolkit.var"#_RGF_ModTag", (0xcb0eae81, 0xc1f457d0, 0x4567074d, 0xab381c5c, 0x7871df2a)}}, LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Vector{Symbol}, Symbol, Vector{Any}, ModelingToolkit.var"#526#generated_observed#494"{Bool, ODESystem, Dict{Any, Any}}, Nothing, ODESystem}, Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, MethodOfLines.MOLMetadata{Val{true}(), MethodOfLines.DiscreteSpace{1, 3, MethodOfLines.CenterAlignedGrid}, MOLFiniteDifference{MethodOfLines.CenterAlignedGrid, MethodOfLines.ScalarizedDiscretization}, PDESystem, Base.RefValue{Any}, MethodOfLines.ScalarizedDiscretization}}, Tsit5{typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.trivial_limiter!), Static.False}, OrdinaryDiffEq.InterpolationData{ODEFunction{true, SciMLBase.AutoSpecialize, ModelingToolkit.var"#f#486"{RuntimeGeneratedFunctions.RuntimeGeneratedFunction{(:ˍ₋arg1, :ˍ₋arg2, :t), ModelingToolkit.var"#_RGF_ModTag", ModelingToolkit.var"#_RGF_ModTag", (0xeacbf879, 0x8cf5ba36, 0xa4c23b0f, 0x3fc01e9a, 0x21768875)}, RuntimeGeneratedFunctions.RuntimeGeneratedFunction{(:ˍ₋out, :ˍ₋arg1, :ˍ₋arg2, :t), ModelingToolkit.var"#_RGF_ModTag", ModelingToolkit.var"#_RGF_ModTag", (0xcb0eae81, 0xc1f457d0, 0x4567074d, 0xab381c5c, 0x7871df2a)}}, LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Vector{Symbol}, Symbol, Vector{Any}, ModelingToolkit.var"#526#generated_observed#494"{Bool, ODESystem, Dict{Any, Any}}, Nothing, ODESystem}, Vector{Vector{Float64}}, Vector{Float64}, Vector{Vector{Vector{Float64}}}, OrdinaryDiffEq.Tsit5Cache{Vector{Float64}, Vector{Float64}, Vector{Float64}, OrdinaryDiffEq.Tsit5ConstantCache{Float64, Float64}, typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.trivial_limiter!), Static.False}}, DiffEqBase.DEStats, Nothing}, ODEFunction{true, SciMLBase.AutoSpecialize, ModelingToolkit.var"#f#486"{RuntimeGeneratedFunctions.RuntimeGeneratedFunction{(:ˍ₋arg1, :ˍ₋arg2, :t), ModelingToolkit.var"#_RGF_ModTag", ModelingToolkit.var"#_RGF_ModTag", (0xeacbf879, 0x8cf5ba36, 0xa4c23b0f, 0x3fc01e9a, 0x21768875)}, RuntimeGeneratedFunctions.RuntimeGeneratedFunction{(:ˍ₋out, :ˍ₋arg1, :ˍ₋arg2, :t), ModelingToolkit.var"#_RGF_ModTag", ModelingToolkit.var"#_RGF_ModTag", (0xcb0eae81, 0xc1f457d0, 0x4567074d, 0xab381c5c, 0x7871df2a)}}, LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Vector{Symbol}, Symbol, Vector{Any}, ModelingToolkit.var"#526#generated_observed#494"{Bool, ODESystem, Dict{Any, Any}}, Nothing, ODESystem}, OrdinaryDiffEq.Tsit5Cache{Vector{Float64}, Vector{Float64}, Vector{Float64}, OrdinaryDiffEq.Tsit5ConstantCache{Float64, Float64}, typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.trivial_limiter!), Static.False}, OrdinaryDiffEq.DEOptions{Float64, Float64, Float64, Float64, PIController{Rational{Int64}}, typeof(DiffEqBase.ODE_DEFAULT_NORM), typeof(LinearAlgebra.opnorm), Nothing, CallbackSet{Tuple{}, Tuple{}}, typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN), typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE), typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK), DataStructures.BinaryHeap{Float64, DataStructures.FasterForward}, DataStructures.BinaryHeap{Float64, DataStructures.FasterForward}, Nothing, Nothing, Int64, Tuple{}, Tuple{}, Tuple{}}, Vector{Float64}, Float64, Nothing, OrdinaryDiffEq.DefaultInit}, cache::OrdinaryDiffEq.Tsit5Cache{Vector{Float64}, Vector{Float64}, Vector{Float64}, OrdinaryDiffEq.Tsit5ConstantCache{Float64, Float64}, typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.trivial_limiter!), Static.False})
    @ OrdinaryDiffEq ~/.julia/packages/OrdinaryDiffEq/P7HJO/src/perform_step/low_order_rk_perform_step.jl:736
 [12] __init(prob::ODEProblem{Vector{Float64}, Tuple{Float64, Float64}, true, SciMLBase.NullParameters, ODEFunction{true, SciMLBase.AutoSpecialize, ModelingToolkit.var"#f#486"{RuntimeGeneratedFunctions.RuntimeGeneratedFunction{(:ˍ₋arg1, :ˍ₋arg2, :t), ModelingToolkit.var"#_RGF_ModTag", ModelingToolkit.var"#_RGF_ModTag", (0xeacbf879, 0x8cf5ba36, 0xa4c23b0f, 0x3fc01e9a, 0x21768875)}, RuntimeGeneratedFunctions.RuntimeGeneratedFunction{(:ˍ₋out, :ˍ₋arg1, :ˍ₋arg2, :t), ModelingToolkit.var"#_RGF_ModTag", ModelingToolkit.var"#_RGF_ModTag", (0xcb0eae81, 0xc1f457d0, 0x4567074d, 0xab381c5c, 0x7871df2a)}}, LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Vector{Symbol}, Symbol, Vector{Any}, ModelingToolkit.var"#526#generated_observed#494"{Bool, ODESystem, Dict{Any, Any}}, Nothing, ODESystem}, Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, MethodOfLines.MOLMetadata{Val{true}(), MethodOfLines.DiscreteSpace{1, 3, MethodOfLines.CenterAlignedGrid}, MOLFiniteDifference{MethodOfLines.CenterAlignedGrid, MethodOfLines.ScalarizedDiscretization}, PDESystem, Base.RefValue{Any}, MethodOfLines.ScalarizedDiscretization}}, alg::Tsit5{typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.trivial_limiter!), Static.False}, timeseries_init::Tuple{}, ts_init::Tuple{}, ks_init::Tuple{}, recompile::Type{Val{true}}; saveat::Tuple{}, tstops::Tuple{}, d_discontinuities::Tuple{}, save_idxs::Nothing, save_everystep::Bool, save_on::Bool, save_start::Bool, save_end::Nothing, callback::Nothing, dense::Bool, calck::Bool, dt::Float64, dtmin::Nothing, dtmax::Float64, force_dtmin::Bool, adaptive::Bool, gamma::Rational{Int64}, abstol::Nothing, reltol::Nothing, qmin::Rational{Int64}, qmax::Int64, qsteady_min::Int64, qsteady_max::Int64, beta1::Nothing, beta2::Nothing, qoldinit::Rational{Int64}, controller::Nothing, fullnormalize::Bool, failfactor::Int64, maxiters::Int64, internalnorm::typeof(DiffEqBase.ODE_DEFAULT_NORM), internalopnorm::typeof(LinearAlgebra.opnorm), isoutofdomain::typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN), unstable_check::typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK), verbose::Bool, timeseries_errors::Bool, dense_errors::Bool, advance_to_tstop::Bool, stop_at_next_tstop::Bool, initialize_save::Bool, progress::Bool, progress_steps::Int64, progress_name::String, progress_message::typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE), userdata::Nothing, allow_extrapolation::Bool, initialize_integrator::Bool, alias_u0::Bool, alias_du0::Bool, initializealg::OrdinaryDiffEq.DefaultInit, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ OrdinaryDiffEq ~/.julia/packages/OrdinaryDiffEq/P7HJO/src/solve.jl:493
 [13] __init(prob::ODEProblem{Vector{Float64}, Tuple{Float64, Float64}, true, SciMLBase.NullParameters, ODEFunction{true, SciMLBase.AutoSpecialize, ModelingToolkit.var"#f#486"{RuntimeGeneratedFunctions.RuntimeGeneratedFunction{(:ˍ₋arg1, :ˍ₋arg2, :t), ModelingToolkit.var"#_RGF_ModTag", ModelingToolkit.var"#_RGF_ModTag", (0xeacbf879, 0x8cf5ba36, 0xa4c23b0f, 0x3fc01e9a, 0x21768875)}, RuntimeGeneratedFunctions.RuntimeGeneratedFunction{(:ˍ₋out, :ˍ₋arg1, :ˍ₋arg2, :t), ModelingToolkit.var"#_RGF_ModTag", ModelingToolkit.var"#_RGF_ModTag", (0xcb0eae81, 0xc1f457d0, 0x4567074d, 0xab381c5c, 0x7871df2a)}}, LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Vector{Symbol}, Symbol, Vector{Any}, ModelingToolkit.var"#526#generated_observed#494"{Bool, ODESystem, Dict{Any, Any}}, Nothing, ODESystem}, Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, MethodOfLines.MOLMetadata{Val{true}(), MethodOfLines.DiscreteSpace{1, 3, MethodOfLines.CenterAlignedGrid}, MOLFiniteDifference{MethodOfLines.CenterAlignedGrid, MethodOfLines.ScalarizedDiscretization}, PDESystem, Base.RefValue{Any}, MethodOfLines.ScalarizedDiscretization}}, alg::Tsit5{typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.trivial_limiter!), Static.False}, timeseries_init::Tuple{}, ts_init::Tuple{}, ks_init::Tuple{}, recompile::Type{Val{true}}) (repeats 5 times)
    @ OrdinaryDiffEq ~/.julia/packages/OrdinaryDiffEq/P7HJO/src/solve.jl:73
 [14] #__solve#501
    @ ~/.julia/packages/OrdinaryDiffEq/P7HJO/src/solve.jl:5 [inlined]
 [15] __solve
    @ ~/.julia/packages/OrdinaryDiffEq/P7HJO/src/solve.jl:5 [inlined]
 [16] #solve_call#26
    @ ~/.julia/packages/DiffEqBase/WXn2i/src/solve.jl:473 [inlined]
 [17] solve_call
    @ ~/.julia/packages/DiffEqBase/WXn2i/src/solve.jl:445 [inlined]
 [18] #solve_up#32
    @ ~/.julia/packages/DiffEqBase/WXn2i/src/solve.jl:835 [inlined]
 [19] solve_up
    @ ~/.julia/packages/DiffEqBase/WXn2i/src/solve.jl:810 [inlined]
 [20] #solve#31
    @ ~/.julia/packages/DiffEqBase/WXn2i/src/solve.jl:802 [inlined]
 [21] solve(prob::ODEProblem{Vector{Float64}, Tuple{Float64, Float64}, true, SciMLBase.NullParameters, ODEFunction{true, SciMLBase.AutoSpecialize, ModelingToolkit.var"#f#486"{RuntimeGeneratedFunctions.RuntimeGeneratedFunction{(:ˍ₋arg1, :ˍ₋arg2, :t), ModelingToolkit.var"#_RGF_ModTag", ModelingToolkit.var"#_RGF_ModTag", (0xeacbf879, 0x8cf5ba36, 0xa4c23b0f, 0x3fc01e9a, 0x21768875)}, RuntimeGeneratedFunctions.RuntimeGeneratedFunction{(:ˍ₋out, :ˍ₋arg1, :ˍ₋arg2, :t), ModelingToolkit.var"#_RGF_ModTag", ModelingToolkit.var"#_RGF_ModTag", (0xcb0eae81, 0xc1f457d0, 0x4567074d, 0xab381c5c, 0x7871df2a)}}, LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Vector{Symbol}, Symbol, Vector{Any}, ModelingToolkit.var"#526#generated_observed#494"{Bool, ODESystem, Dict{Any, Any}}, Nothing, ODESystem}, Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, MethodOfLines.MOLMetadata{Val{true}(), MethodOfLines.DiscreteSpace{1, 3, MethodOfLines.CenterAlignedGrid}, MOLFiniteDifference{MethodOfLines.CenterAlignedGrid, MethodOfLines.ScalarizedDiscretization}, PDESystem, Base.RefValue{Any}, MethodOfLines.ScalarizedDiscretization}}, args::Tsit5{typeof(OrdinaryDiffEq.trivial_limiter!), typeof(OrdinaryDiffEq.trivial_limiter!), Static.False})
    @ DiffEqBase ~/.julia/packages/DiffEqBase/WXn2i/src/solve.jl:794
 [22] top-level scope
    @ REPL[1]:1
```

**Comment by sdwfrost** [comment]
Example 2 fails at discretize:

```julia
using ModelingToolkit
using MethodOfLines
using DomainSets
using OrdinaryDiffEq

β = 0.0005
γ = 0.25
amin = 0.0
amax = 40.0

@parameters t a
@variables S(..) I(..) R(..)
Dt = Differential(t)
Da = Differential(a)
Ia = Integral(a in DomainSets.ClosedInterval(amin,amax))


eqs = [Dt(S(t)) ~ -β * S(t) * Ia(I(a,t)),
       Dt(I(a,t)) + Da(I(a,t)) ~ -γ*I(a,t),
       Dt(R(t)) ~ γ*Ia(I(a,t))]

bcs = [
        S(0) ~ 990.0,
        I(0,t) ~ β*S(t)*Ia(I(a,t)),
        I(a,0) ~ 10.0/40.0,
        R(0) ~ 0.0
        ]

domains = [t ∈ (0,40.0), a ∈ (0,40.0)]

@named pde_system = PDESystem(eqs, bcs, domains, [a, t], [S(t), I(a, t), R(t)])

da = 0.1
discretization = MOLFiniteDifference([a=>da], t)

prob = MethodOfLines.discretize(pde_system, discretization)
```

Output:

```julia
julia> prob = MethodOfLines.discretize(pde_system, discretization)
ERROR: iteration is deliberately unsupported for CartesianIndex. Use `I` rather than `I...`, or use `Tuple(I)...`
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] iterate(#unused#::CartesianIndex{0})
    @ Base.IteratorsMD ./multidimensional.jl:167
  [3] setdiff!(s::Set{CartesianIndex{0}}, itr::CartesianIndex{0})
    @ Base ./abstractset.jl:196
  [4] _shrink(shrinker!::Function, itr::Array{CartesianIndex{0}, 0}, itrs::Tuple{CartesianIndex{0}})
    @ Base ./array.jl:2632
  [5] setdiff(itr::Array{CartesianIndex{0}, 0}, itrs::CartesianIndex{0})
    @ Base ./array.jl:2637
  [6] generate_extrap_eqs!(eqs::Vector{Any}, pde::Equation, u::Term{Real, Base.ImmutableDict{DataType, Any}}, s::MethodOfLines.DiscreteSpace{1, 3, MethodOfLines.CenterAlignedGrid}, derivweights::MethodOfLines.DifferentialDiscretizer{Pair{Sym{Real, Base.ImmutableDict{DataType, Any}}, Vector{Int64}}, Dict{Function, MethodOfLines.DerivativeOperator{Float64, Nothing, false, Float64, StaticArraysCore.SVector{3, Float64}, S2, S3, Nothing, Nothing} where {S2, S3}}, UpwindScheme}, interiormap::MethodOfLines.InteriorMap, bcmap::Dict{Sym{SymbolicUtils.FnType{Tuple, Real}, Nothing}, Dict{Sym{Real, Base.ImmutableDict{DataType, Any}}, Vector{Any}}})
    @ MethodOfLines ~/.julia/packages/MethodOfLines/2pXtX/src/discretization/generate_bc_eqs.jl:194
  [7] discretize_equation!(alleqs::Vector{Any}, bceqs::Vector{Any}, pde::Equation, interiormap::MethodOfLines.InteriorMap, eqvar::Term{Real, Base.ImmutableDict{DataType, Any}}, bcmap::Dict{Sym{SymbolicUtils.FnType{Tuple, Real}, Nothing}, Dict{Sym{Real, Base.ImmutableDict{DataType, Any}}, Vector{Any}}}, depvars::Vector{Any}, s::MethodOfLines.DiscreteSpace{1, 3, MethodOfLines.CenterAlignedGrid}, derivweights::MethodOfLines.DifferentialDiscretizer{Pair{Sym{Real, Base.ImmutableDict{DataType, Any}}, Vector{Int64}}, Dict{Function, MethodOfLines.DerivativeOperator{Float64, Nothing, false, Float64, StaticArraysCore.SVector{3, Float64}, S2, S3, Nothing, Nothing} where {S2, S3}}, UpwindScheme}, indexmap::Dict{Sym{Real, Base.ImmutableDict{DataType, Any}}, Int64})
    @ MethodOfLines ~/.julia/packages/MethodOfLines/2pXtX/src/scalar_discretization.jl:12
  [8] symbolic_discretize(pdesys::PDESystem, discretization::MOLFiniteDifference{MethodOfLines.CenterAlignedGrid, MethodOfLines.ScalarizedDiscretization})
    @ MethodOfLines ~/.julia/packages/MethodOfLines/2pXtX/src/MOL_discretization.jl:133
  [9] discretize(pdesys::PDESystem, discretization::MOLFiniteDifference{MethodOfLines.CenterAlignedGrid, MethodOfLines.ScalarizedDiscretization}; analytic::Nothing, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ MethodOfLines ~/.julia/packages/MethodOfLines/2pXtX/src/MOL_discretization.jl:152
 [10] discretize(pdesys::PDESystem, discretization::MOLFiniteDifference{MethodOfLines.CenterAlignedGrid, MethodOfLines.ScalarizedDiscretization})
    @ MethodOfLines ~/.julia/packages/MethodOfLines/2pXtX/src/MOL_discretization.jl:152
 [11] top-level scope
    @ REPL[2]:1
```

**Comment by xtalax** [comment]
Not sure what's going on in ex 1, I suspect a symbol typing error somewhere

For example 2, I realise that I didn't account for integrals in BCs, I will fix this and try to find the working code.

Thanks for posting these, they will be important in improving robustness·

**Comment by BernhardAhrens** [comment]
@sdwfrost Your Example 1 solves for me when I change
```domains = [t ∈ (0,40.0), a ∈ (0,75*52)]```
to 
```domains = [t ∈ (0,40.0), a ∈ (0.0,75*52.0)]```

I.e. Float64, not Int64.

**Comment by sdwfrost** [comment]
@BernhardAhrens - thanks, this now solves for me too, though now I can see that the code isn't giving the correct answer - probably a misspecification on my side.

**Comment by xtalax** [comment]
I am actively working on this, this may take a bit longer since it makes certain indexing assumptions used throughout invalid

**Pull request merged**
