### PR TITLE
Complex Number Support

### LINKED ISSUE #58: One-dimensional NLS using MethodOfLines ‘type Array has no field lhs`
I’m trying to solve the one-dimensional nonlinear Schrodinger equation using _MethodOfLines.jl_. I looked at the code on the docs: [http://methodoflines.sciml.ai/dev/tutorials/brusselator/ 3](http://methodoflines.sciml.ai/dev/tutorials/brusselator/), and adapted it as:

```
using ModelingToolkit, MethodOfLines, OrdinaryDiffEq, DomainSets

@parameters x z
@variables A(..)
Dx   = Differential(x)
Dz   = Differential(z)
Dzz  = Differential(z)^2

xmin = 0.
xmax = 1e-1
zmax = 10.
zmin = -zmax

c0 = 1.
A0(x,z) = c0*sech(c0*z/sqrt(2))*exp(im*c0^2*x/2)

domains = [x ∈ Interval(xmin,xmax), z ∈ Interval(zmin,zmax)]

eq = [im*Dx(A(x,z))+Dzz(A(x,z)) ~ -abs2(A(x,z))*A(x,z)]
bcs = [A(xmin,z) ~ A0(xmin,z), 
        A(x,zmin) ~ 0, 
        A(x,zmax) ~ 0]

@named pdesys = PDESystem(eq,bcs,domains,[x,z],[A(x,z)])

N       = 100
dz      = 1/N
order   = 2

discretization = MOLFiniteDifference([z=>dz], x)

@time prob = discretize(pdesys,discretization)
```

However this won’t run, giving error `type Array has no field lhs`. I think the only main difference between my code and the tutorial is that my PDE is for a single function.

I'm running Julia v1.7.2, with package versions:
- DiffEqOperators v4.41.0
- MethodOfLines v0.2.0
- ~~ModelingToolkit v6.7.1~~ ModelingToolkit v8.5.5
- DomainSets v0.5.9

The full error is:
```
ERROR: type Array has no field lhs
Stacktrace:
  [1] getproperty
    @ .\Base.jl:42 [inlined]
  [2] (::MethodOfLines.var"#65#67"{Vector{Sym{SymbolicUtils.FnType{Tuple, Real}, Nothing}}})(x::Vector{Equation})
    @ MethodOfLines C:\Users\ruvil\.julia\packages\MethodOfLines\9MLPx\src\MOL_utils.jl:64
  [3] mapreduce_first(f::MethodOfLines.var"#65#67"{Vector{Sym{SymbolicUtils.FnType{Tuple, Real}, Nothing}}}, op::Function, x::Vector{Equation})
    @ Base .\reduce.jl:394
  [4] _mapreduce(f::MethodOfLines.var"#65#67"{Vector{Sym{SymbolicUtils.FnType{Tuple, Real}, Nothing}}}, op::typeof(union), #unused#::IndexLinear, A::Vector{Vector{Equation}})
    @ Base .\reduce.jl:405
  [5] _mapreduce_dim(f::Function, op::Function, #unused#::Base._InitialValue, A::Vector{Vector{Equation}}, #unused#::Colon)
    @ Base .\reducedim.jl:330
  [6] #mapreduce#725
    @ .\reducedim.jl:322 [inlined]
  [7] mapreduce(f::Function, op::Function, A::Vector{Vector{Equation}})
    @ Base .\reducedim.jl:322
  [8] get_all_depvars(pdesys::PDESystem, depvar_ops::Vector{Sym{SymbolicUtils.FnType{Tuple, Real}, Nothing}})
    @ MethodOfLines C:\Users\ruvil\.julia\packages\MethodOfLines\9MLPx\src\MOL_utils.jl:64
  [9] symbolic_discretize(pdesys::PDESystem, discretization::MOLFiniteDifference{MethodOfLines.CenterAlignedGrid})
    @ MethodOfLines C:\Users\ruvil\.julia\packages\MethodOfLines\9MLPx\src\discretization\MOL_discretization.jl:18
 [10] discretize(pdesys::PDESystem, discretization::MOLFiniteDifference{MethodOfLines.CenterAlignedGrid})
    @ MethodOfLines C:\Users\ruvil\.julia\packages\MethodOfLines\9MLPx\src\discretization\MOL_discretization.jl:146
 [11] top-level scope
    @ .\timing.jl:220

```

### LINKED ISSUE #101: Complex Number support
These are currently unsupported, see #80 for example code

### PR DESCRIPTION
**Pull request by xtalax**
Adds complex number support, does this by splitting the system in to real and imaginary parts.

fixes #58
fixes #101

### CODE REVIEW

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by xtalax** [comment]
held up by https://github.com/JuliaSymbolics/SymbolicUtils.jl/issues/498

**Comment by curio-sitas** [comment]
I tried your PR for my 3 complex wave nonlinear coupled equations. It seems that there is a problem with the discretization 👍 

Code : 
```julia
using OrdinaryDiffEq, ModelingToolkit, MethodOfLines, DomainSets

# Parameters, variables, and derivatives
@parameters t z
@variables Ap(..) As(..) Q(..)

Dt = Differential(t)
Dz = Differential(z)


eqs = [
Dz(Ap(z,t)) ~ im*As(z,t)*Q(z,t) - Dt(Ap(z,t)),
Dz(As(z,t)) ~ Dt(As(z,t)) - im*Ap(z,t)*conj(Q(z,t)),
Dz(Q(z,t)) ~ -Dt(Q(z,t)) - (1+im)*Q(z,t) + im*Ap(z,t)*conj(As(z,t))
]

# Space and time domains
domains = [t ∈ (0.0,50.0),
           z ∈ (0.0,10.0)]

# Initial and boundary conditions
bcs = [
Ap(0,t) ~ sin(t),
As(0,t) ~ cos(t),
Q(0,t) ~ cos(t) 
]

# PDE system
@named pdesys = PDESystem(eqs,bcs,domains,[t,z],[Ap(z,t), As(z,t), Q(z,t)])

# Method of lines discretization
dz = 0.1
order = 2
discretization = MOLFiniteDifference([z=>dz],t)



# Convert the PDE problem into an ODE problem
prob = discretize(pdesys,discretization) # error
```

I have the following error : 
> pdesys = PDESystem(Equation[Differential(z)(ReAp(z, t)) ~ -Differential(t)(ReAp(z, t)), 0 ~ ImAs(z, t)*ImQ(z, t), Differential(z)(ReAs(z, t)) ~ Differential(t)(ReAs(z, t)), 0 ~ -ImAp(z, t)*ImQ(z, t), Differential(z)(ReQ(z, t)) ~ 
-Differential(t)(ReQ(z, t)) - ReQ(z, t), 0 ~ ImAp(z, t)*ImAs(z, t) - ImQ(z, t)], Equation[ReAp(0, t) ~ sin(t), ImAp(0, t) ~ sin(t), ReAs(0, t) ~ cos(t), ImAs(0, t) ~ cos(t), ReQ(0, t) ~ cos(t), ImQ(0, t) ~ cos(t)], Term{Real, Nothing}[ReAp(z, t), ImAp(z, t), ReAs(z, t), ImAs(z, t), ReQ(z, t), ImQ(z, t)], Num[t, z], SciMLBase.NullParameters(), SciMLBase.NullParameters(), Dict{Any, Any}(), nothing, Any[], :pdesys, nothing)
ERROR: MethodError: no method matching length(::SciMLBase.NullParameters)
Closest candidates are:
  length(::Union{Base.KeySet, Base.ValueIterator}) at abstractdict.jl:58
  length(::Union{IterTools.Properties, IterTools.PropertyValues}) at C:\Users\brsinquin\.julia\packages\IterTools\GLAcp\src\IterTools.jl:999
  length(::Union{ArrayInterfaceCore.BidiagonalIndex, ArrayInterfaceCore.TridiagonalIndex}) at C:\Users\brsinquin\.julia\packages\ArrayInterfaceCore\o8YXM\src\ArrayInterfaceCore.jl:666
  ...
Stacktrace:
  [1] length(g::Base.Generator{SciMLBase.NullParameters, MethodOfLines.var"#64#65"})
    @ Base .\generator.jl:50
  [2] _similar_shape(itr::Base.Generator{SciMLBase.NullParameters, MethodOfLines.var"#64#65"}, #unused#::Base.HasLength)
    @ Base .\array.jl:663
  [3] collect(itr::Base.Generator{SciMLBase.NullParameters, MethodOfLines.var"#64#65"})
    @ Base .\array.jl:786
  [4] map(f::Function, A::SciMLBase.NullParameters)
    @ Base .\abstractarray.jl:2961
  [5] get_ops(depvars::SciMLBase.NullParameters)
    @ MethodOfLines C:\Users\brsinquin\.julia\packages\MethodOfLines\ddPIJ\src\MOL_symbolic_utils.jl:120
  [6] MethodOfLines.VariableMap(eqs::Vector{Equation}, depvars::SciMLBase.NullParameters, domain::Vector{Term{Real, Nothing}}, time::Num)
    @ MethodOfLines C:\Users\brsinquin\.julia\packages\MethodOfLines\ddPIJ\src\system_parsing\variable_map.jl:14
  [7] MethodOfLines.VariableMap(pdesys::PDESystem, t::Num)
    @ MethodOfLines C:\Users\brsinquin\.julia\packages\MethodOfLines\ddPIJ\src\system_parsing\variable_map.jl:34
  [8] symbolic_discretize(pdesys::PDESystem, discretization::MOLFiniteDifference{MethodOfLines.CenterAlignedGrid, MethodOfLines.ScalarizedDiscretization})
    @ MethodOfLines C:\Users\brsinquin\.julia\packages\MethodOfLines\ddPIJ\src\MOL_discretization.jl:37
  [9] discretize(pdesys::PDESystem, discretization::MOLFiniteDifference{MethodOfLines.CenterAlignedGrid, MethodOfLines.ScalarizedDiscretization}; analytic::Nothing, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ MethodOfLines C:\Users\brsinquin\.julia\packages\MethodOfLines\ddPIJ\src\MOL_discretization.jl:154
 [10] discretize(pdesys::PDESystem, discretization::MOLFiniteDifference{MethodOfLines.CenterAlignedGrid, MethodOfLines.ScalarizedDiscretization})
    @ MethodOfLines C:\Users\brsinquin\.julia\packages\MethodOfLines\ddPIJ\src\MOL_discretization.jl:153
 [11] top-level scope
    @ d:\Home\brsinquin\Desktop\Brillouin.jl:42

**Comment by curio-sitas** [comment]
> Yes, this is not currently working as it is held up by an error fixed by [this](https://github.com/JuliaSymbolics/Symbolics.jl/pull/789), so we are waiting for this to merge to get complex working.
> 
> I notice too that you have not supplied initial conditions for your variables, you need to do this if you want a result
> 
> If you'd like to help you could find an example complex system with a known analytic solution to improve the robustness of the tests - I'll happily code it up

The Nonlinear Schrödinger Equation (for propagation of light in a 3rd order nonlinear medium for example) is one of these problems. It also has a set of analytical solutions, named Solitons. (https://hal.science/hal-02440836/document). I use to simulate this system for my PhD research, i'll be pleased to/help to implement this example.

**Comment by curio-sitas** [comment]
Any news ? It seems that the Symbolics.jl [issue](https://github.com/JuliaSymbolics/Symbolics.jl/pull/789) has been merged.

**Comment by xtalax** [comment]
I will get to this soon

**Pull request closed without merging**
