### PR TITLE
fornberg(2020) weights based on hermite-based finite difference

### PR DESCRIPTION
**Pull request by yewalenikhil65**
same PR from https://github.com/SciML/DiffEqOperators.jl/pull/501 and also https://github.com/SciML/MethodOfLines.jl/issues/13

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@xtalax review?

**Comment by yewalenikhil65** [comment]
hey @ChrisRackauckas 
@xtalax  reviewed partially on DiffEqOperator.jl [here](https://github.com/SciML/DiffEqOperators.jl/pull/501)
I would like to work on extending this a bit in actually solving PDE, but currently caught up in some other work. I will get back to it late this month. 
Till then this PR is good to be to merge as it won't break anything.

**Comment by xtalax** [comment]
Sorry about the delay, looks good to me

**Comment by yewalenikhil65** [comment]
> Sorry about the delay, looks good to me

@xtalax I see new some changes from my last commits in fornberg file. i will do same, resolve some conflicts and re-submit new commits

**Comment by yewalenikhil65** [comment]
@xtalax Done from my side for this PR !

**Pull request merged**
