### PR TITLE
Upwind Differences

### PR DESCRIPTION
**Pull request by xtalax**
## Summary
This PR implements upwind differencing for odd order derivatives, and a simple implementation of periodic boundary conditions.

Note that upwinding for higher approximation order currently leads to instability due to the necessary boundary winding, this could perhaps be mitigated by further shrinking the interior in this case.

## Status
Tests passing except:
- Test 03 of 1D linear convection erroring, seemingly by evaluating the conditional in the `ifelse` to a `Num` type and trying to evaluate it before substituting in the fact that `v` is `0.0` everywhere
- Test 04 failing, despite plots showing near perfect agreement between analytic and solution, error clearly below margin EDIT: Passing

### CODE REVIEW

**Comment by xtalax** [comment]
To elaborate on the error of test 03, which tests `Dt(u(t,x)) ~ -Dx(v(t,x))*u(t,x)-v(t,x)*Dx(u(t,x)) with v(t,x)=1` with periodic boundary conditions, which are verified above; Method of lines is creating equations of the form:
- On the interior of `u`: `Dt(u) ~ IfElse.ifelse(v[5](t) > 0, v[5](t)*forward_diff, v[5](t)*reverse_diff)`

- On the interior of `v`: `v[5](t) ~ 1.0`

In other words, the system looks correct.

Full stacktrace:
```
Test 03: Dt(u(t,x)) ~ -Dx(v(t,x))*u(t,x)-v(t,x)*Dx(u(t,x)) with v(t,x)=1: Error During Test at /mnt/manjarohome/alex/.julia/dev/MethodOfLines.jl/test/pde_systems/MOL_1D_Linear_Convection.jl:194
  Got exception outside of a @test
  TypeError: non-boolean (Symbolics.Num) used in boolean context
  Stacktrace:
    [1] isequal(a::SymbolicUtils.Add{Real, Int64, Dict{Any, Number}, Nothing}, b::SymbolicUtils.Add{Real, Symbolics.Num, Dict{Any, Number}, Nothing})
      @ SymbolicUtils ~/.julia/packages/SymbolicUtils/lCYjx/src/types.jl:650
    [2] fixpoint_sub(x::SymbolicUtils.Add{Real, Int64, Dict{Any, Number}, Nothing}, dict::Dict{SymbolicUtils.Term{Real, Base.ImmutableDict{DataType, Any}}, Float64})
      @ ModelingToolkit ~/.julia/packages/ModelingToolkit/m9TvT/src/systems/alias_elimination.jl:494
    [3] tearing_sub(expr::SymbolicUtils.Add{Real, Int64, Dict{Any, Number}, Nothing}, dict::Dict{SymbolicUtils.Term{Real, Base.ImmutableDict{DataType, Any}}, Float64}, s::Bool)
      @ ModelingToolkit.StructuralTransformations ~/.julia/packages/ModelingToolkit/m9TvT/src/structural_transformation/symbolics_tearing.jl:33
    [4] (::ModelingToolkit.StructuralTransformations.var"#79#81"{Bool, Dict{SymbolicUtils.Term{Real, Base.ImmutableDict{DataType, Any}}, Float64}})(eq::Symbolics.Equation)
      @ ModelingToolkit.StructuralTransformations ~/.julia/packages/ModelingToolkit/m9TvT/src/structural_transformation/symbolics_tearing.jl:45
    [5] iterate
      @ ./generator.jl:47 [inlined]
    [6] _collect(c::Vector{Symbolics.Equation}, itr::Base.Generator{Vector{Symbolics.Equation}, ModelingToolkit.StructuralTransformations.var"#79#81"{Bool, Dict{SymbolicUtils.Term{Real, Base.ImmutableDict{DataType, Any}}, Float64}}}, #unused#::Base.EltypeUnknown, isz::Base.HasShape{1})
      @ Base ./array.jl:744
    [7] collect_similar(cont::Vector{Symbolics.Equation}, itr::Base.Generator{Vector{Symbolics.Equation}, ModelingToolkit.StructuralTransformations.var"#79#81"{Bool, Dict{SymbolicUtils.Term{Real, Base.ImmutableDict{DataType, Any}}, Float64}}})
      @ Base ./array.jl:653
    [8] map(f::Function, A::Vector{Symbolics.Equation})
      @ Base ./abstractarray.jl:2849
    [9] full_equations(sys::ModelingToolkit.ODESystem; simplify::Bool)
      @ ModelingToolkit.StructuralTransformations ~/.julia/packages/ModelingToolkit/m9TvT/src/structural_transformation/symbolics_tearing.jl:43
   [10] full_equations
      @ ~/.julia/packages/ModelingToolkit/m9TvT/src/structural_transformation/symbolics_tearing.jl:38 [inlined]
   [11] calculate_massmatrix(sys::ModelingToolkit.ODESystem; simplify::Bool)
      @ ModelingToolkit ~/.julia/packages/ModelingToolkit/m9TvT/src/systems/diffeqs/abstractodesystem.jl:267
   [12] calculate_massmatrix
      @ ~/.julia/packages/ModelingToolkit/m9TvT/src/systems/diffeqs/abstractodesystem.jl:267 [inlined]
   [13] (SciMLBase.ODEFunction{true})(sys::ModelingToolkit.ODESystem, dvs::Vector{SymbolicUtils.Term{Real, Base.ImmutableDict{DataType, Any}}}, ps::Vector{Any}, u0::Vector{Float64}; version::Nothing, tgrad::Bool, jac::Bool, eval_expression::Bool, sparse::Bool, simplify::Bool, eval_module::Module, steady_state::Bool, checkbounds::Bool, sparsity::Bool, kwargs::Base.Pairs{Symbol, Any, NTuple{4, Symbol}, NamedTuple{(:ddvs, :linenumbers, :parallel, :has_difference), Tuple{Nothing, Bool, Symbolics.SerialForm, Bool}}})
      @ ModelingToolkit ~/.julia/packages/ModelingToolkit/m9TvT/src/systems/diffeqs/abstractodesystem.jl:359
   [14] process_DEProblem(constructor::Type, sys::ModelingToolkit.ODESystem, u0map::Vector{Pair}, parammap::SciMLBase.NullParameters; implicit_dae::Bool, du0map::Nothing, version::Nothing, tgrad::Bool, jac::Bool, checkbounds::Bool, sparse::Bool, simplify::Bool, linenumbers::Bool, parallel::Symbolics.SerialForm, eval_expression::Bool, kwargs::Base.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:has_difference,), Tuple{Bool}}})
      @ ModelingToolkit ~/.julia/packages/ModelingToolkit/m9TvT/src/systems/diffeqs/abstractodesystem.jl:593
   [15] (SciMLBase.ODEProblem{true})(sys::ModelingToolkit.ODESystem, u0map::Vector{Pair}, tspan::Tuple{Float64, Float64}, parammap::SciMLBase.NullParameters; callback::Nothing, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ ModelingToolkit ~/.julia/packages/ModelingToolkit/m9TvT/src/systems/diffeqs/abstractodesystem.jl:671
   [16] (SciMLBase.ODEProblem{true})(sys::ModelingToolkit.ODESystem, u0map::Vector{Pair}, tspan::Tuple{Float64, Float64}, parammap::SciMLBase.NullParameters) (repeats 2 times)
      @ ModelingToolkit ~/.julia/packages/ModelingToolkit/m9TvT/src/systems/diffeqs/abstractodesystem.jl:670
   [17] SciMLBase.ODEProblem(::ModelingToolkit.ODESystem, ::Vector{Pair}, ::Vararg{Any}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ ModelingToolkit ~/.julia/packages/ModelingToolkit/m9TvT/src/systems/diffeqs/abstractodesystem.jl:649
   [18] SciMLBase.ODEProblem(::ModelingToolkit.ODESystem, ::Vector{Pair}, ::Vararg{Any})
      @ ModelingToolkit ~/.julia/packages/ModelingToolkit/m9TvT/src/systems/diffeqs/abstractodesystem.jl:649
   [19] discretize(pdesys::ModelingToolkit.PDESystem, discretization::MethodOfLines.MOLFiniteDifference{MethodOfLines.CenterAlignedGrid})
      @ MethodOfLines /mnt/manjarohome/alex/.julia/dev/MethodOfLines.jl/src/MOL_discretization.jl:111
   [20] macro expansion
      @ /mnt/manjarohome/alex/.julia/dev/MethodOfLines.jl/test/pde_systems/MOL_1D_Linear_Convection.jl:229 [inlined]
   [21] macro expansion
      @ /usr/share/julia/stdlib/v1.7/Test/src/Test.jl:1283 [inlined]
   [22] top-level scope
      @ /mnt/manjarohome/alex/.julia/dev/MethodOfLines.jl/test/pde_systems/MOL_1D_Linear_Convection.jl:196
   [23] include(mod::Module, _path::String)
      @ Base ./Base.jl:418
   [24] include(x::String)
      @ Main.##277 ~/.julia/packages/SafeTestsets/A83XK/src/SafeTestsets.jl:23
   [25] macro expansion
      @ /mnt/manjarohome/alex/.julia/dev/MethodOfLines.jl/test/runtests.jl:20 [inlined]
   [26] macro expansion
      @ /usr/share/julia/stdlib/v1.7/Test/src/Test.jl:1283 [inlined]
   [27] top-level scope
      @ /mnt/manjarohome/alex/.julia/dev/MethodOfLines.jl/test/runtests.jl:20
   [28] eval(m::Module, e::Any)
      @ Core ./boot.jl:373
   [29] macro expansion
      @ ~/.julia/packages/SafeTestsets/A83XK/src/SafeTestsets.jl:23 [inlined]
   [30] macro expansion
      @ timing.jl:220 [inlined]
   [31] macro expansion
      @ /mnt/manjarohome/alex/.julia/dev/MethodOfLines.jl/test/runtests.jl:20 [inlined]
   [32] top-level scope
      @ timing.jl:220
   [33] include(fname::String)
      @ Base.MainInclude ./client.jl:451
   [34] top-level scope
      @ none:6
   [35] eval
      @ ./boot.jl:373 [inlined]
   [36] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:268
   [37] _start()
      @ Base ./client.jl:495
```

**Comment by xtalax** [comment]
The plot for test 04:
MOL_Linear_Convection_Test04

**Comment by ChrisRackauckas** [comment]
What if you use `IfElse.ifelse`? It shouldn't be required on v1.7, but I guess it's needed for backwards compatibility.

https://github.com/SciML/IfElse.jl

**Comment by xtalax** [comment]
I do use `IfElse.ifelse`

**Comment by ChrisRackauckas** [comment]
Can you construct an MWE?

**Comment by xtalax** [comment]
What do you mean by MWE?

**Comment by ChrisRackauckas** [comment]
Minimal working example, i.e. minimal example that demonstrates the issue. Try and strip out all of the MOL stuff

**Comment by xtalax** [comment]
Of course, my bad. I'll get that done tomorrow

**Comment by xtalax** [comment]
Where I'm at:
MWE with MOL, this is the simplest system that throws the error.
```
using ModelingToolkit, MethodOfLines, OrdinaryDiffEq, DomainSets

@parameters t x
@variables v(..) u(..)
Dt = Differential(t)
Dx = Differential(x)

# 1D PDE and boundary conditions
eq  = [ Dt(u(t,x)) ~ -u(t,x) + v(t,x)*Dx(u(t,x)),
        v(t,x) ~ 1.0 ]

bcs = [u(0,x) ~ 1.0,
       u(t,0) ~ u(t,2),
       v(0,x) ~ 1.0,
       v(t,0) ~ 1.0,
       v(t,2) ~ 1.0
       ]

# Space and time domains
domains = [t ∈ Interval(0.0,2.0),
           x ∈ Interval(0.0,2.0)]


# PDE system
@named pdesys = PDESystem(eq,bcs,domains,[t,x],[u(t,x),v(t,x)])

# Method of lines discretization
order = 1
discretization = MOLFiniteDifference([x=>1.0],t)

# Convert the PDE problem into an ODE problem
prob = discretize(pdesys,discretization)

# Solve ODE problem
sol = solve(prob,Euler(),dt=.025,saveat=0.1)
```
Throws the error, the function call in question and prints:
```
        println(vcat(alleqs, unique(bceqs)))
        println(Dict(defaults))#
        println(vec(reduce(vcat, vec(alldepvarsdisc))))
        println(ps)
        println(tspan)
        sys = ODESystem(vcat(alleqs, unique(bceqs)), t, vec(reduce(vcat, vec(alldepvarsdisc))), ps, defaults=Dict(defaults), name=pdesys.name)
       
       simpsys = structural_simplify(sys)
       
       prob = ODEProblem(simpsys,Pair[],tspan) # Throws the error
```
The output of the prints:
```
Equation[Differential(t)(u[2](t)) ~ IfElse.ifelse(v[2](t) > 0, (u[3](t) - u[2](t))*v[2](t), (u[2](t) - u[1](t))*v[2](t)) - u[2](t), v[2](t) ~ 1.0, u[1](t) ~ u[3](t), v[1](t) ~ 1.0, v[3](t) ~ 1.0]
Dict{Num, Float64}(u[1](t) => 1.0, u[2](t) => 1.0, v[2](t) => 1.0, v[3](t) => 1.0, u[3](t) => 1.0, v[1](t) => 1.0)

Num[u[1](t), u[2](t), u[3](t), v[1](t), v[2](t), v[3](t)]

Num[]

(0.0, 2.0)
```
MWE without MOL:
```
using IfElse, ModelingToolkit, OrdinaryDiffEq

@parameters t
 

u = collect(first(@variables u[1:3](t)))
v = collect(first(@variables v[1:3](t)))
Dt = Differential(t)

eq = [Dt(u[2]) ~ IfElse.ifelse(v[2] > 0, (u[3] - u[2])*v[2], (u[2] - u[1])*v[2]) - u[2], 
      v[2] ~ 1.0, 
      u[1] ~ u[3], 
      v[1] ~ 1.0, 
      v[3] ~ 1.0]
      
u0 = vcat(u .=> 1.0, v .=> 1.0)
      
tspan = (0.0, 2.0)

println(eq)
println(Dict(u0))
println(tspan)

sys = ODESystem(eq, t, vcat(u, v), Num[], defaults=Dict(u0), name=:sys)
simpsys = structural_simplify(sys)

prob = ODEProblem(simpsys, Pair[], tspan)
```
Output of the prints is identical to the above. `structural_simplify` throws:
```
ERROR: LoadError: ExtraVariablesSystemException: The system is unbalanced. There are 5 highest order derivative variables and 4 equations.
More variables than equations, here are the potential extra variable(s):
 u[2](t)
 u[1](t)
```
Adding an extra equation for `u[1]` correctly generates the `prob`

**Comment by xtalax** [comment]
Thanks Timo, this is just the form that the tests were written in - doesn't seem to affect things

**Comment by xtalax** [comment]
Solving this equation:
```
v = 1.0

# 1D PDE and boundary conditions
eq  = Dt(u(t,x)) ~ 0.0001*u(t,x)-v*Dx(u(t,x))
```
Doesn't lead to the same error, looking at the generated equations, the simple constant `v` has lead the `ifelse` to be simplified away before the system construction, further implying that this has something to do with the symbolic conditional in the `ifelse`

**Comment by xtalax** [comment]
Test 04 is failing because the boundary equation for `v` is removing the interior equation at `u[end]`, meaning that the periodic bc fails. This will be complicated to corerect, involving recognising when a periodic bc is present so `u[end]` remains on the interior and substituting in boundary conditions for `v` at this index. 

This also strongly implies that periodic bcs won't work properly for higher order derivatives, where there are multiple bcs for a different variable on the same dimension as the periodic.

This will require a complete rethink of BCs, moving to substituting them in rather than using ghost nodes unless I am mistaken. Open to hearing less disgusting alternatives.

**Comment by tinosulzer** [comment]
> Would this mean that an x dependent v would also need to be differentiated with the product rule?

Yes, it needs to be differentiated, although it's debatable whether using the product rule is optimal here (for example you could instead do e.g. `(u[i+1]v[i+1] - u[i]v[i]) / dx`

**Comment by xtalax** [comment]
That's much better, and more doable with existing code

**Comment by ChrisRackauckas** [comment]
>Test 04 is failing because the boundary equation for v is removing the interior equation at u[end], meaning that the periodic bc fails. This will be complicated to corerect, involving recognising when a periodic bc is present so u[end] remains on the interior and substituting in boundary conditions for v at this index.

Show an example?

**Comment by xtalax** [comment]
An example system?

**Comment by ChrisRackauckas** [comment]
and example of how the discretization falls apart in that case.

**Comment by xtalax** [comment]
MOL_Linear_Convection_Test04

There is no interior update equation, so `u[0]` and `u[end]` remain at their initial values

**Comment by ChrisRackauckas** [comment]
but only one of them get deleted because there's one BC?

**Comment by xtalax** [comment]
There was in the correct case no interior equation at `u[1]`, as the periodic bc removes this equation. the BC `v(t, 2) ~ 1.0` also removes the equation at `u[end]`.

**Comment by ChrisRackauckas** [comment]
> The BC v(t, 2) ~ 1.0 also removes the equation at u[end].

Shouldn't that just remove `v[end]`? I'm confused.

**Comment by xtalax** [comment]
Yes, it should. This is because the current implementation looks at all bcs but in the case where the equation at `u[end]` is in terms `v` still removes that from the interior, as it doesn't differentiate between bcs defined on the different variables. 

That's one fix and is fine as long as a periodic bc is the only bc defined for a given variable. If this should always be the case then there's no problem.

**Comment by ChrisRackauckas** [comment]
> That's one fix and is fine as long as a periodic bc is the only bc defined for a given variable. If this should always be the case then there's no problem

That needs to be the case or the PDE would be over-specified and may not have a solution.

> is it sufficient to remove only interior points for bcs on the variable on which they are defined, or can you think of cases where this wouldn't do?

I think it's sufficient.

**Comment by xtalax** [comment]
Just need to work out what to do when there is no continuous variable.

It's fairly clear that an equation containing the time derivative of some `u` should remove the boundaries for that variable from its interior, but how to recognize that an equation governs some `u` more than another, and should use its interior when there is no `t` variable?

**Comment by xtalax** [comment]
Soving the above by creating a unique mapping between eqauations and dependant variables based on which variable has highest order in each pde, with precedant given to order in time

**Pull request merged**
